# The dedicated workflow for the whole acceptance test-suite. Only run on
# schedule or manually, but never with any customization.
name: Acceptance Tests in RMA1

on:
  # Scheduled tests (UTC)
  schedule:
    - cron: '0 15 * * *'

  # Manual execution through the UI by collaborators
  workflow_dispatch:

jobs:
  acceptance-tests-in-rma1:
    uses: ./.github/workflows/run-acceptance-tests.yml
    with:
      zone: rma1
    secrets:
      api_token: ${{ secrets.CLOUDSCALE_API_TOKEN_AT_RMA1 }}
